### ISSUE TITLE
Create a README.md

### ISSUE THREAD

**Issue by Naereen** [ThibaultGROUEIX/python_tuto#1]

**Comment by ThibaultGROUEIX** [comment]
added in commit 4ed498c9a1cac526d649d145707bd132ca69bb95

**Comment by Naereen** [comment]
![unicorn](https://cloud.githubusercontent.com/assets/11994719/26632297/de2f0702-460f-11e7-9926-76eca34fa34a.png)
OH MY GOSH you broke GitHub... for 5 seconds.
